### ISSUE TITLE
[DOCS] The UX can be improved by several methods

### ISSUE THREAD

**Issue by Dharmik48** [AkshDesai04/Project-WatchDog#9]
There are a couple of ways by which the experience of the user can be improved:

- A table of contents can be added at the top for easy navigation.
- The `Getting started` section can be enhanced by adding code snippets for the installation and also adding a sub-section `Prerequisites` (if any)
- You can use [this](https://contrib.rocks/) tool which adds pfps of all the awesome people who contributes to the project

**Comment by AkshDesai04** [comment]
added the [contrib.rocks](contrib.rocks) top contributor pfp to the readme and will be updating it periodically.
Thanks for the cool tool 😄

**Comment by Dharmik48** [comment]
> added the [contrib.rocks](contrib.rocks) top contributor pfp to the readme and will be updating it periodically.

The good thing about that tool is it auto updates the list

**Comment by AkshDesai04** [comment]
That's great
Thanks for the help😄

**Comment by AkshDesai04** [comment]
Hey, if all issues seem to have been resolved, please close the Issue.
